# Generated by Django 3.2.20 on 2023-09-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_creation_date_term_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Term',
            new_name='FAQ',
        ),
    ]
